### ISSUE TITLE
Prisma warning for no highlighting support

### ISSUE THREAD

**Issue by Avivhdr** [mariorodeghiero/vue-theme-vscode#14]
<img width="476" alt="image" src="https://github.com/mariorodeghiero/vue-theme-vscode/assets/23265867/56e4f823-05cf-4c5f-a9a2-a3d5877b41c7">

**Comment by mariorodeghiero** [comment]
hi @Avivhdr Have you tried this https://github.com/prisma/language-tools/issues/133#issuecomment-1396342818? 

if don't work, can you add more context, please?

**Comment by mariorodeghiero** [comment]
Hi @Avivhdr have tried the solution above? 
The issue will be close soon, please let me know.

**Comment by Avivhdr** [comment]
I tried it and it worked. 
I still get the error message though.

Thank you!

**Comment by mariorodeghiero** [comment]
good that it works.

Unfortunately is not easy to find a solution for the error message.
