### ISSUE TITLE
Color scheme for Screen reader button contrast

### ISSUE THREAD

**Issue by alanmbarr** [mariorodeghiero/vue-theme-vscode#2]
If you see the screenreader button the light blue on green is a little hard to read
![image](https://user-images.githubusercontent.com/760506/43666024-b67d98a2-9737-11e8-9e4f-38a0cf154e51.png)

**Comment by mariorodeghiero** [comment]
cool, after I fix this, I return with a print for you to give a feedback.

**Comment by mariorodeghiero** [comment]
Hey @alanmbarr , v1.1.0 available! Corrected button to the default colors as attached print. 
<img width="1092" alt="screen shot 2018-08-24 at 23 30 16" src="https://user-images.githubusercontent.com/24671133/44614374-9f883800-a7f9-11e8-9ed6-35c6ad73ebb8.png">

Thanks ✌️
