### ISSUE TITLE
Improve typescript colors

### ISSUE THREAD

**Issue by mariorodeghiero** [mariorodeghiero/vue-theme-vscode#6]
Improve typescript colors

1 - The colors are changed in the file **"vue-theme-color-theme.json" **.
2 - In vscode editor, press "CMD+shift+p" and select "Developer: inspect TM scopes" to analyze the scope to change.
3 - After to change, run command "vsce packeg".
4 - Install the file vue-themev-x.x.x.vix to test.
5 - If ok, send me a PR.

**Comment by DennGuez** [comment]
Hey 👋, is  there a way to keep the original colors when changing to TS, for example in the <script setup> when I add the lang TS the imports change to white, and I would like it to stay red as in js, thanks.

**Comment by mariorodeghiero** [comment]
Hi @DennGuez I am not sure if I got the issue correct, but if you use the "inspect TM scopes" in `<script setup>` you can get the correct scope name. So go to **"vue-theme-color-theme.json" ** and add the color that you would like to keep or change.

 I am working on branch V2 and there is an update on the CONTRIBUTING file because VS_code changes how to test it a bit. Check the steps below:
 
Let me know if it helps?

```
## How to test the changes 

1. Open your VS Code
2. Click on the tab View → Run
3. Click Launch Extension. This will open up another VS Code Editor
4. Make changes and it will reflected in the other editor that opened in step 3.
```

**Comment by mariorodeghiero** [comment]
@DennGuez a lot of improvements are coming on V2 for .ts, .tsx, and other languages.
So I will close this issue soon.

**Comment by mariorodeghiero** [comment]
V2 published I hope it improves the styles.
